package pojo;
// Generated 05-Jun-2013 11:53:00 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import pojo.Category;
import pojo.User;

/**
 * Test generated by hbm2java
 */
public class Test  implements java.io.Serializable {


     private Integer id;
     private User user;
     private Category category;
     private String description;
     private Date startDay;
     private Date endDay;
     private int noQuestions;
     private int score;

    public Test() {
    }

    public Test(User user, Category category, String description, Date startDay, Date endDay, int noQuestions, int score) {
       this.user = user;
       this.category = category;
       this.description = description;
       this.startDay = startDay;
       this.endDay = endDay;
       this.noQuestions = noQuestions;
       this.score = score;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getStartDay() {
        return this.startDay;
    }
    
    public void setStartDay(Date startDay) {
        this.startDay = startDay;
    }
    public Date getEndDay() {
        return this.endDay;
    }
    
    public void setEndDay(Date endDay) {
        this.endDay = endDay;
    }
    public int getNoQuestions() {
        return this.noQuestions;
    }
    
    public void setNoQuestions(int noQuestions) {
        this.noQuestions = noQuestions;
    }
    public int getScore() {
        return this.score;
    }
    
    public void setScore(int score) {
        this.score = score;
    }

    @Override
    public String toString() {
        return description;
    }

    


}


