package newp;
// Generated 05-Jun-2013 11:53:00 by Hibernate Tools 3.2.1.GA



/**
 * Answer generated by hbm2java
 */
public class Answer  implements java.io.Serializable {


     private Integer id;
     private Question question;
     private String text;
     private boolean status;

    public Answer() {
    }

    public Answer(Question question, String text, boolean status) {
       this.question = question;
       this.text = text;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Question getQuestion() {
        return this.question;
    }
    
    public void setQuestion(Question question) {
        this.question = question;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }




}


