package newp;
// Generated 05-Jun-2013 11:53:00 by Hibernate Tools 3.2.1.GA


import pojo.Test;
import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Integer id;
     private Domain domain;
     private String name;
     private String description;
     private Set<Question> questions = new HashSet<Question>(0);
     private Set<Test> tests = new HashSet<Test>(0);

    public Category() {
    }

	
    public Category(Domain domain, String name, String description) {
        this.domain = domain;
        this.name = name;
        this.description = description;
    }
    public Category(Domain domain, String name, String description, Set<Question> questions, Set<Test> tests) {
       this.domain = domain;
       this.name = name;
       this.description = description;
       this.questions = questions;
       this.tests = tests;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Domain getDomain() {
        return this.domain;
    }
    
    public void setDomain(Domain domain) {
        this.domain = domain;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set<Question> getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Set<Question> questions) {
        this.questions = questions;
    }
    public Set<Test> getTests() {
        return this.tests;
    }
    
    public void setTests(Set<Test> tests) {
        this.tests = tests;
    }




}


