package newp;
// Generated 05-Jun-2013 11:53:00 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Domain generated by hbm2java
 */
public class Domain  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<Category> categories = new HashSet<Category>(0);

    public Domain() {
    }

	
    public Domain(String name) {
        this.name = name;
    }
    public Domain(String name, Set<Category> categories) {
       this.name = name;
       this.categories = categories;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Category> getCategories() {
        return this.categories;
    }
    
    public void setCategories(Set<Category> categories) {
        this.categories = categories;
    }




}


