package newp;
// Generated 05-Jun-2013 11:53:00 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Question generated by hbm2java
 */
public class Question  implements java.io.Serializable {


     private Integer id;
     private User user;
     private Category category;
     private String text;
     private int difficultyLevel;
     private Set<Answer> answers = new HashSet<Answer>(0);

    public Question() {
    }

	
    public Question(User user, Category category, String text, int difficultyLevel) {
        this.user = user;
        this.category = category;
        this.text = text;
        this.difficultyLevel = difficultyLevel;
    }
    public Question(User user, Category category, String text, int difficultyLevel, Set<Answer> answers) {
       this.user = user;
       this.category = category;
       this.text = text;
       this.difficultyLevel = difficultyLevel;
       this.answers = answers;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public int getDifficultyLevel() {
        return this.difficultyLevel;
    }
    
    public void setDifficultyLevel(int difficultyLevel) {
        this.difficultyLevel = difficultyLevel;
    }
    public Set<Answer> getAnswers() {
        return this.answers;
    }
    
    public void setAnswers(Set<Answer> answers) {
        this.answers = answers;
    }




}


