package newp;
// Generated 05-Jun-2013 11:53:00 by Hibernate Tools 3.2.1.GA


import pojo.Test;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String password;
     private boolean type;
     private Set<Question> questions = new HashSet<Question>(0);
     private Set<Test> tests = new HashSet<Test>(0);

    public User() {
    }

	
    public User(String name, String password, boolean type) {
        this.name = name;
        this.password = password;
        this.type = type;
    }
    public User(String name, String password, boolean type, Set<Question> questions, Set<Test> tests) {
       this.name = name;
       this.password = password;
       this.type = type;
       this.questions = questions;
       this.tests = tests;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isType() {
        return this.type;
    }
    
    public void setType(boolean type) {
        this.type = type;
    }
    public Set<Question> getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Set<Question> questions) {
        this.questions = questions;
    }
    public Set<Test> getTests() {
        return this.tests;
    }
    
    public void setTests(Set<Test> tests) {
        this.tests = tests;
    }




}


